### ISSUE TITLE
Create search feature with the described parameters

### ISSUE THREAD

**Issue by VictorGreco** [VictorGreco/music-library#5]
https://docs.google.com/document/d/1SPVnxcaQSDeTcog434uSWWExXoitlKZ5g_XIDB_eUAc/edit#

First you must analyze the following requirements that the company asks you for the search feature of the app:
The web must be dynamic and the actions will be carried out without reloading the page
The search engine must implement the following options:
- Search songs by name
- Search artists by name
- Search albums by name
- Search music videos by name
In addition, the following additional optional parameters must be applicable to the search:
Filter by country
You should consult a specific third-party API to obtain the necessary information to apply the filter.
- Ex: https://www.liferay.com/api/jsonws/country/get-countries/
Filter by explicit content
- “Yes” or “No” options
Filter by results limit
- Range from 1 to 200.

The search must be carried out each time the input changes, that is, each time a character is entered, the page will show the content found.
Any item found by a search can be added to favorites and will be displayed in the favorites section (example in the wireframe)
Items previously found may be deleted from favorites
Favorite items should be stored in localStorage

**Comment by soyyogi** [comment]
Finished
